### ISSUE TITLE
Find or Build manually annotating framework to segment images.

### ISSUE THREAD

**Issue by tesYolan** [singnet/plant-disease-experiments#2]
One of the problems we face when experimenting with the different architectures is generalizing well to new image or dataset. This is primarily due to the network learning *not specially* important features that we would probably would have considered. That is specially pertinent for datasets of small size that we are primarily focused on. 

And specially for GAN variant architectures, the problem is exacerbated by the fact they may not even allow the network to converge. 

To resolve this issue, whatever approach we take here, we need to include segmentation pipeline *before* our different training sessions or *in* our different network architectures. 

For the *before* training sessions, we need to segment the images manually for those that aren't. i.e
 - [x] Explore different segmentation libraries and approaches to automate the process. 
 - [x] Build or Build on top available frameworks to segment our training images

**Comment by IsraelAbebe** [comment]
- have tested semantic segmentation architectures that we can use. most of them are based on the paper [Fully Convolutional Networks for Semantic Segmentation](https://arxiv.org/pdf/1411.4038)
- have found [labelme](https://github.com/wkentaro/labelme) tool that can work annotating the dataset we have so far

**Comment by IsraelAbebe** [comment]
-  we generated a mask for 54,000 datasets (using mask-generator )  and we have annotated by hand using  [labelme](https://github.com/wkentaro/labelme)  additionally 60+ leaf images that we were able to get 
- worked on two different segmentation approaches that are added to this repo as a submodule 
       
       -    leaf-image-segmentation-segnet
                    -  segmentation pipline using VGGSegNet Architecture
       -    leaf-image-segmentation
                    -   histogram based segmentation Pipline

**Challenges**

- we dont have real life sample dataset
