### ISSUE TITLE
file download

### ISSUE THREAD

**Issue by itcalvin** [singnet/plant-disease-experiments#6]
how can i download the file that name is “VGG_all_100p_94.h5”。

**Comment by IsraelAbebe** [comment]
you can download it from [Here](https://drive.google.com/file/d/1AufdWYl-TfeicAmaweq6Gd8q3--vuBfA/view?usp=sharing) extract it in Plant_Disease_Detection_Benchmark_models/Models/    folder and you should be able to do prediction on sample images 

look at at the README for more model updates coming soon
